### ISSUE TITLE
'packages' seems not to be installed

### ISSUE THREAD

**Issue by aerrow5** [wiedi/deploy-zone#18]
Running script based on base-64 goes ok. 
However all requested packages are not installed.

Tried mi-example with packages: 
# List packages to add to your image one per line.
unzip
openjdk8
mongodb
nano

Programs where not available after building image and deploy vm via vmadm.
Hence my 'customize' script failed due to missing unzip (mi-aerrow-unifi).
Running manually on vm command pkg_add -v <packages> went ok without errors.

**Comment by wiedi** [comment]
This should be fixed in the latest version. Please let me know if you still run into issues.

**Comment by aerrow5** [comment]
My running version is 0.1.3. Tried update via npm install -g deploy-zone.
This version still skips the packages.

**Comment by wiedi** [comment]
sorry, version 0.1.4 should be on npm now
