### ISSUE TITLE
requirements.networks is expecting a vnic

### ISSUE THREAD

**Issue by n1ete** [wiedi/deploy-zone#19]
I tried to build the mi-core-gitea image but i failed to build it.

i cloned the repo local and from that dir i run:

`dz-build --host 'HOSTNAME' -o /opt/builder/ .`
and get
`imgadm create: error (1): Command failed: Unable to start VM 7d1f04e6-19ca-4e44-a354-2afbfd10810d: first of 1 error: Command failed: zone '7d1f04e6-19ca-4e44-a354-2afbfd10810d': undefined VNIC net0  (global NIC external)`

so i guess its expected by dz-build that net0 has to be on a vlan?
thanks for any hints ;)

**Comment by drscream** [comment]
It's recommended to use a JSON template for `vmadm` creation. This can be specified with the `-t` option. The template can contain details about the zone, so it can be used to match your current environment.

#### template.json:

```json
{
  "brand": "joyent",
  "resolvers": ["8.8.8.8", "8.8.4.4"],
  "ram": 2048,
  "nics": [{
    "nic_tag": "external",
    "ips": [ "192.168.200.200/24" ],
    "gateways": [ "192.168.200.1" ],
    "primary": true
  }]
}
```

#### usage:

```bash
dz build --host smartos.havanna.dev --template ~/.dz/template.json -o /opt/tmp .
```

**Comment by n1ete** [comment]
Thanks!
